camera:
  filters:
    hole_filling:
      enabled: false
    spatial:
      enabled: true
    temporal:
      enabled: true
  fps: 15
  resolution: 640x480
color_frame:
  stream_enabled: true
depth_frame:
  stream_enabled: true
min_confidence: 0.85
network_tables:
  server: 10.59.87.2
  table: RealsenseVision
pipeline:
  args:
  - balls_rknn_model
  type: DetectionDepthPipeline
rknn_chip_type: rk3588
