camera:
  filters:
    hole_filling:
      enabled: false
    spatial:
      enabled: true
    temporal:
      enabled: true
  fps: 15
  resolution: 640x480
chip_type: qcs6490
color_frame:
  stream_enabled: true
depth_frame:
  stream_enabled: true
image_size: 640
min_confidence: 0.85
network_tables:
  server: 10.59.87.2
  table: AdvantageKit/RealsenseVision
pipeline:
  args:
  - best.tflite
  type: DetectionDepthPipeline
